name: CIHI RSS Feed Updater

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run RSS Feed Updater
        run: node fetch_rss.js  # Make sure this script correctly generates cihi_data_feed.xml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cihi_data_feed.xml  # Ensure correct file name
          git commit -m "Daily RSS feed update [skip ci]" || exit 0
          git push
